In [1]:
import numpy as np 
import pandas as pd 
import tensorflow as tf

In [3]:
train_dataset = pd.read_csv("dataset/mnist_train.csv")
test_dataset = pd.read_csv("dataset/mnist_test.csv")

print(train_dataset.shape)

(60000, 785)


In [64]:
X_train = train_dataset.iloc[: ,1:].to_numpy()
X_train = X_train/ 255
y_train = train_dataset.iloc[: ,0].to_numpy()

X_test = test_dataset.iloc[: ,1:].to_numpy()
X_test = X_test/ 255
y_test = test_dataset.iloc[: ,0].to_numpy()


print(X_train.shape)
print(X_train[:5])
print(y_train.shape)
print(y_train[:5])

(60000, 784)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(60000,)
[5 0 4 1 9]


In [68]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(units = 40, activation = "relu"),
    tf.keras.layers.Dense(units = 10, activation = "softmax")
])

model.summary()

Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_34 (Dense)            (None, 40)                31400     
                                                                 
 dense_35 (Dense)            (None, 10)                410       
                                                                 
Total params: 31,810
Trainable params: 31,810
Non-trainable params: 0
_________________________________________________________________


In [69]:
model.compile(
    loss = tf.keras.losses.sparse_categorical_crossentropy,
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.002),
    metrics = ['accuracy']
)

model.fit(
    X_train, y_train, epochs = 20
)

Epoch 1/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2707 - accuracy: 0.9234
Epoch 2/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1409 - accuracy: 0.9576
Epoch 3/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1087 - accuracy: 0.9679
Epoch 4/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0917 - accuracy: 0.9724
Epoch 5/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0787 - accuracy: 0.9765
Epoch 6/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0702 - accuracy: 0.9786
Epoch 7/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0619 - accuracy: 0.9805
Epoch 8/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0568 - accuracy: 0.9815
Epoch 9/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0515 - accuracy: 0.9833
Epoch 10/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.046

In [71]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.1651 - accuracy: 0.9686


[0.16507716476917267, 0.9685999751091003]